'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function AuthPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mode, setMode] = useState('password'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event) => { event.preventDefault(); setBusy(true); setMessage(''); const supabase = createClient(); const result = mode === 'magic' ? await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/auth/callback` } }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); setMessage(result.error ? result.error.message : mode === 'magic' ? 'Check your inbox for the secure sign-in link.' : 'Signed in. You can return to the guide.') }
  return <main className="flex min-h-screen items-center justify-center bg-[#f0fdf4] px-4"><div className="w-full max-w-md rounded-3xl border border-emerald-100 bg-white p-7 shadow-lg"><a href="/" className="font-bold text-[#0f5132]">← Hajj & Umrah Guide</a><h1 className="mt-8 text-3xl font-bold text-slate-900">Welcome back</h1><p className="mt-2 text-slate-600">Sign in to sync your progress and pilgrimage profile.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-semibold text-slate-700">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="focus-ring mt-2 w-full rounded-xl border border-slate-300 p-3" /></label>{mode === 'password' && <label className="block text-sm font-semibold text-slate-700">Password<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="focus-ring mt-2 w-full rounded-xl border border-slate-300 p-3" /></label>}<button disabled={busy} className="focus-ring w-full rounded-xl bg-[#0f5132] p-3 font-bold text-white disabled:opacity-60">{busy ? 'Please wait…' : mode === 'magic' ? 'Send magic link' : 'Sign in'}</button></form>{message && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{message}</p>}<button onClick={() => setMode(mode === 'magic' ? 'password' : 'magic')} className="focus-ring mt-5 text-sm font-semibold text-emerald-800 underline">{mode === 'magic' ? 'Use password instead' : 'Use a magic link instead'}</button></div></main>
}
