'use client'

import { useState } from 'react'
import { Check, Lock, MapPin, Moon, ShieldCheck, Users } from 'lucide-react'
import { useGeoLocation, isWithinRadius } from '@/hooks/useGeoLocation'

const kaaba = { latitude: 21.422487, longitude: 39.826206 }
const sites = [{ name: 'Masjid al-Haram', point: kaaba, radius: 300 }, { name: 'Mina', point: { latitude: 21.4133, longitude: 39.8932 }, radius: 700 }, { name: 'Arafat', point: { latitude: 21.3548, longitude: 39.9841 }, radius: 1200 }, { name: 'Muzdalifah', point: { latitude: 21.3891, longitude: 39.9126 }, radius: 900 }, { name: 'Jamarat', point: { latitude: 21.4137, longitude: 39.8789 }, radius: 500 }]

function Counter({ title, total }) {
  const [count, setCount] = useState(0)
  const advance = () => { if (count < total) { setCount(count + 1); if (navigator.vibrate) navigator.vibrate(35) } }
  return <article className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">{title}</p><p className="mt-2 text-4xl font-bold text-slate-900">{count}<span className="text-lg text-slate-400">/{total}</span></p></div><button onClick={advance} disabled={count === total} className="focus-ring rounded-xl bg-[#0f5132] px-5 py-3 font-bold text-white disabled:bg-slate-300">{count === total ? 'Complete' : 'Count'}</button></div><div className="mt-4 h-2 rounded-full bg-emerald-50"><div className="h-2 rounded-full bg-[#15803d] transition-all" style={{ width: `${count / total * 100}%` }} /></div></article>
}

export default function Dashboard() {
  const { location, loading, error } = useGeoLocation({ watch: true })
  const [largeText, setLargeText] = useState(false)
  const nearby = sites.find((site) => isWithinRadius(location, site.point, site.radius))
  return <main className={largeText ? 'large-text min-h-screen' : 'min-h-screen'}>
    <nav className="sticky top-0 z-10 border-b border-emerald-100 bg-white/95 px-4 py-4 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="focus-ring flex items-center gap-2 font-bold text-[#0f5132]"><Moon className="h-6 w-6" /> Hajj & Umrah Guide</a><div className="flex items-center gap-3"><button onClick={() => setLargeText(!largeText)} className="focus-ring rounded-lg border border-emerald-200 px-3 py-2 text-sm font-semibold">A+ Text</button><a href="/pricing" className="focus-ring rounded-lg bg-[#0f5132] px-3 py-2 text-sm font-semibold text-white">Plans</a></div></div></nav>
    <div className="mx-auto max-w-6xl px-4 py-8 sm:py-12"><section className="rounded-3xl bg-[#0f5132] p-6 text-white shadow-xl sm:p-10"><p className="mb-3 flex items-center gap-2 text-sm font-semibold text-emerald-200"><ShieldCheck className="h-5 w-5" /> Your calm companion for worship</p><h1 className="max-w-2xl text-3xl font-bold tracking-tight sm:text-5xl">Be present for every step of your pilgrimage.</h1><p className="mt-4 max-w-xl text-emerald-50">Simple guidance, respectful reminders, and progress tools designed for the journey.</p></section>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-emerald-100 bg-white p-5 md:col-span-2"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-emerald-700">Location companion</p><h2 className="mt-1 text-xl font-bold text-slate-900">{nearby ? `You may be near ${nearby.name}` : 'Location is ready when you are'}</h2></div><MapPin className="h-7 w-7 text-emerald-600" /></div><p className="mt-3 text-slate-600">{loading ? 'Requesting your location…' : error ? error.message : location ? `Accuracy: approximately ${Math.round(location.accuracy)} metres` : 'Allow location access to receive site-aware reminders.'}</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><p className="text-sm font-semibold text-emerald-700">Current plan</p><p className="mt-2 text-2xl font-bold text-[#0f5132]">Free</p><a href="/pricing" className="mt-3 inline-block font-semibold text-emerald-800 underline">Explore Lite & Pro →</a></div></section>
    <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">Ritual companion</p><h2 className="text-2xl font-bold text-slate-900">Keep your progress</h2></div><span className="text-sm text-slate-500">Your counters stay on this device</span></div><div className="grid gap-4 md:grid-cols-2"><Counter title="Tawaf circuits" total={7} /><Counter title="Sa'i laps" total={7} /></div></section>
    <section className="mt-8 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-emerald-100 bg-white p-5"><h2 className="text-lg font-bold text-slate-900">Today’s gentle reminder</h2><p className="mt-2 leading-7 text-slate-600">Move with patience, make space for others, and keep your intention close. There is no required dua for every circuit; remember Allah in the words that come naturally.</p></article><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900"><Lock className="h-5 w-5 text-amber-700" /> More when you need it</h2><p className="mt-2 text-slate-700">GPS ritual tracking is included with Lite. Group location, crowd alerts, and the AI assistant are Pro features.</p><a href="/pricing" className="mt-3 inline-flex items-center gap-2 font-bold text-amber-800 underline"><Users className="h-4 w-4" /> Compare plans</a></article></section></div>
  </main>
}
