'use client'

import { useState } from 'react'
import { Check } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

const plans = [{ id: 'free', name: 'Free', price: '$0', description: 'A clear foundation for every pilgrim', features: ['Step-by-step ritual guides', 'Tawaf and Sa’i counters', 'Standard dua library'] }, { id: 'lite', name: 'Lite', price: '$9', description: 'Confident guidance with GPS support', features: ['Everything in Free', 'Real-time GPS ritual tracking', 'Offline audio guides', 'Personalized itinerary'] }, { id: 'pro', name: 'Pro', price: '$29', description: 'A connected companion for your group', features: ['Everything in Lite', 'Family group tracking', 'Crowd-density alerts', 'AI ritual assistant', 'Priority support'] }]
export default function PricingPage() { const [message, setMessage] = useState(''); const choose = async (tier) => { if (tier === 'free') return setMessage('Free plan selected.'); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return setMessage('Sign in first, then return here to select a plan.'); const { error } = await supabase.from('profiles').update({ subscription_tier: tier }).eq('user_id', user.id); setMessage(error ? error.message : `Mock upgrade complete: you are now on ${tier}. Connect your payment provider before production billing.`) }
return <main className="min-h-screen bg-[#f8fafc] px-4 py-10"><div className="mx-auto max-w-6xl"><a href="/" className="font-bold text-[#0f5132]">← Back to guide</a><header className="mx-auto mt-10 max-w-2xl text-center"><p className="font-semibold uppercase tracking-widest text-emerald-700">Plans for your journey</p><h1 className="mt-3 text-4xl font-bold text-slate-900">Helpful tools, never clutter.</h1><p className="mt-4 text-slate-600">Start free. Upgrade when location awareness or group support will bring you peace of mind.</p></header><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.id} className={`rounded-3xl border bg-white p-6 shadow-sm ${plan.id === 'pro' ? 'border-emerald-600 ring-2 ring-emerald-100' : 'border-slate-200'}`}><h2 className="text-2xl font-bold text-slate-900">{plan.name}</h2><p className="mt-2 text-slate-600">{plan.description}</p><p className="mt-6 text-4xl font-bold text-[#0f5132]">{plan.price}<span className="text-sm font-normal text-slate-500"> / month</span></p><ul className="mt-7 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-slate-700"><Check className="h-5 w-5 shrink-0 text-emerald-600" />{feature}</li>)}</ul><button onClick={() => choose(plan.id)} className="focus-ring mt-8 w-full rounded-xl bg-[#0f5132] p-3 font-bold text-white">{plan.id === 'free' ? 'Get started' : `Choose ${plan.name}`}</button></article>)}</div>{message && <p className="mx-auto mt-6 max-w-xl rounded-xl bg-emerald-50 p-4 text-center text-emerald-900">{message}</p>}</div></main> }
